name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Of de branch waarvan je wilt dat deze deployt naar gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'

      - name: Deploy to gh-pages
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push -f origin gh-pages

